feat: add eslint plugin
amplication/plugins pull request #135
Opened 2023-08-05 06:37 UTC by Shurtu-gal

### Description
This module adds eslint as static files and updates package.json.

### Fixes
closes amplication/amplication#6605

2023-08-06 09:07 UTC, morhag90 requested changes

2023-08-06 09:07 UTC, morhag90 commented on plugins/linter-eslint/README.md
@Shurtu-gal  Please update this file with the relevant information

2023-08-06 09:07 UTC, morhag90 commented on plugins/linter-eslint/src/events/createAdminUI.ts
@Shurtu-gal  Looks like the same logic as in the afterCreate server function. Please write one function for both events (and pass the baseDirectory according to the event: server/client).

2023-08-06 09:10 UTC, Shurtu-gal commented on plugins/linter-eslint/README.md
Sure

2023-08-06 09:11 UTC, Shurtu-gal commented on plugins/linter-eslint/src/events/createAdminUI.ts
Okay

2023-08-07 08:01 UTC, morhag90 approved these changes

2023-08-07 08:02 UTC, morhag90 commented
@Shurtu-gal  Great work!!

2023-08-07 09:05 UTC, Shurtu-gal commented
Thanks

2023-08-11 12:50 UTC, merged