feat: add settings functionality
amplication/plugins pull request #143
Opened 2023-08-13 20:25 UTC by Shurtu-gal

### Description
- Have added custom settings for prettier.

### Fixes
closes amplication/amplication#6606

2023-08-15 09:21 UTC, overbit commented
@Shurtu-gal can you please add some unit test to cover the expected results?

2023-08-15 09:22 UTC, Shurtu-gal commented
Sure I would do so..

2023-08-15 14:37 UTC, Shurtu-gal commented
@overbit just had a tiny doubt regarding how to mock importStaticModules in the tests?

2023-08-17 07:40 UTC, overbit commented
@Shurtu-gal you could avoid mocking it and use the real method for it. Any thoughts on this option?

2023-08-17 12:48 UTC, Shurtu-gal commented
> @Shurtu-gal you could avoid mocking it and use the real method for it. Any thoughts on this option?

Can you tell me where to import it from?

2023-08-18 10:22 UTC, overbit commented
> > @Shurtu-gal you could avoid mocking it and use the real method for it. Any thoughts on this option?
> 
> Can you tell me where to import it from?

Answered offline.

2023-08-18 10:23 UTC, overbit commented
@Shurtu-gal, once this is completed, would you be able to open a new PR for tests in the eslint too?

2023-08-21 14:07 UTC, overbit requested changes

2023-08-21 14:07 UTC, overbit commented on plugins/formatter-prettier/.amplicationrc.json
> +      "trailingComma": "all"
Let's use the default rules `{}`

2023-08-21 14:16 UTC, Shurtu-gal commented on plugins/formatter-prettier/.amplicationrc.json
> +      "trailingComma": "all"
Okay

2023-08-21 14:18 UTC, Shurtu-gal commented on plugins/formatter-prettier/.amplicationrc.json
> +      "trailingComma": "all"
@overbit Done

2023-08-22 10:18 UTC, overbit approved these changes
Nice work @Shurtu-gal!

2023-08-22 10:18 UTC, merged