Feat(plugin): rabbitmq plugin
amplication/plugins pull request #187
Opened 2023-10-07 17:10 UTC by Meyazhagan

Added RabbitMQ plugin

2023-10-17 12:05 UTC, abrl91 submitted a review, later dismissed
@Meyazhagan 
Well done!

Just two comments:
1. please make the `RABBITMQ_URLS` visible on the settings. You need to create `.amplicationrc` file (have a look at the postres plugin
2. in the producer service, you have this import: `import { MyMessageBrokerTopics } from "./topics";` if the user changes the name of the broker,  the import will be broken. You need to import based on the name of the broker. You can take it from the context

2023-10-23 09:41 UTC, overbit requested changes

2023-10-23 09:41 UTC, overbit commented on plugins/broker-rabbitmq/webpack.config.js
Please align this configuration with the latest master the plugin-template webpack.config.js

2023-10-23 14:47 UTC, overbit commented
Once done, you can easily request a re-review clicking the button aside the reviewrs
<img width="1113" alt="image" src="https://github.com/amplication/plugins/assets/2861984/f6bc254e-41ed-40ee-94fa-ad181091d822">

2023-10-30 10:35 UTC, overbit requested changes

2023-10-30 13:43 UTC, overbit commented
Thank you and well done @Meyazhagan!!!
I'm going to merge and publish this plugin soon

2023-10-30 13:43 UTC, overbit approved these changes

2023-10-30 13:43 UTC, merged