Prettier plugin
amplication/plugins pull request #24
Opened 2022-11-30 15:28 UTC by EugeneTseitlin

2022-12-01 16:26 UTC, overbit requested changes

2022-12-12 12:22 UTC, EugeneTseitlin commented on .amplicationconfig.json
> +      "distPath": "./plugins/prettier/dist"
It's just an instruction for plugin test runner which plugins to use. We can remove config from repo and write an instruction how to use it. But in in the scope of this issue :)

2022-12-12 12:34 UTC, EugeneTseitlin commented on plugins/prettier/package.json
> +  "description": "Description of your plugin",
Done

2022-12-12 12:35 UTC, EugeneTseitlin commented on plugins/prettier/package.json
> +  "author": "Amplication Contributor",
Done

2022-12-12 12:35 UTC, EugeneTseitlin commented on plugins/prettier/package.json
> +  "description": "Description of your plugin",
Done

2022-12-12 14:57 UTC, merged