fix(dsg) remove all ts-ignore and lint ignore comments from template …
amplication/plugins pull request #315
Opened 2023-12-25 06:10 UTC by Meyazhagan

…files and in static folders

Fixes: amplication/amplication#7668

## PR Details

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm build` doesn't throw any error
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2024-02-01 12:14 UTC, overbit requested changes

2024-02-03 14:31 UTC, Meyazhagan commented
@overbit I done the changes! have a look

2024-02-09 14:06 UTC, overbit approved these changes

2024-02-09 14:07 UTC, merged

2024-02-09 14:07 UTC, overbit commented
well done @Meyazhagan 🚀