feat(plugins): add keycloak plugin
amplication/plugins pull request #318
Opened 2023-12-27 22:26 UTC by Shurtu-gal

Fixes: amplication/amplication#7044

## PR Details

Add Keycloak plugin for authentication

## PR Checklist

- [x] Make the plugin
- [ ] Add README
- [ ] Tests for the changes have been added
- [x] `npm build` doesn't throw any error
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-12-28 08:27 UTC, overbit commented
@Shurtu-gal do you mind rebasing on master as we just merged a PR that clean all linting/testing issues?

2023-12-28 10:10 UTC, Shurtu-gal commented
Done @overbit. What about templates, I guess they should also be put in `.eslintignore`

2023-12-28 11:31 UTC, overbit commented
@Shurtu-gal that is a good point. Can you raise a new PR just for that (eslint ignore in the template)?

2023-12-28 11:39 UTC, Shurtu-gal commented
Sure.

2024-01-04 10:38 UTC, overbit requested changes
@Shurtu-gal really good work. Just a couple of comments but generally looks great

2024-01-04 12:46 UTC, Shurtu-gal commented on plugins/auth-keycloak/src/templates/jwt.strategy.base.template.ts
> +// @ts-ignore
They are being being removed from the generated code out [here](https://github.com/Shurtu-gal/plugins/blob/973c2794fedb448b29a82a87d4d321409697b30c/plugins/auth-keycloak/src/core/create-jwt-strategy-base.ts#L110)

2024-01-04 13:11 UTC, Shurtu-gal commented on plugins/auth-keycloak/src/utils/helpers.ts
> +}
Added `js-convert-case` package as `change-case` was causing problems with `jest`.

2024-01-04 13:11 UTC, Shurtu-gal commented
@overbit The required changes are done.

2024-01-04 13:33 UTC, overbit approved these changes

2024-01-04 13:34 UTC, merged