feat: Github Codespaces Plugin
amplication/plugins pull request #328
Opened 2024-01-10 02:03 UTC by pyxelpioneer

Fixes: amplication/amplication#7012

## PR Details

Adds the plugin as per defined in issue #7012

## PR Checklist

- [X] `npm build` doesn't throw any error
- [X] `npm test` doesn't throw any error
- [X] tested locally

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2024-01-11 08:38 UTC, overbit commented
@pyxelpioneer could you please address the CI failures?

2024-01-11 13:25 UTC, Shurtu-gal requested changes
Nice work 🚀. Just some tiny changes 💯

2024-01-11 13:25 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/src/index.ts
> +      .replace("{CLIENT_ROOT}", context.clientDirectories.baseDirectory)
I don't think `CLIENT_ROOT` is there in init.sh

2024-01-11 13:25 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/package-lock.json
> +  "version": "1.0.0",
Please run `npm i` to update this.

2024-01-11 13:25 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/src/index.ts
> +      code: JSON.stringify(containerConfig),
You can use prettier to prettify the code also.

![image](https://github.com/amplication/plugins/assets/100484401/75b1c312-83d4-4ec2-9229-1b979d49b325)

2024-01-11 13:25 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/src/index.ts
> +      code: JSON.stringify(containerConfig),
Example:- https://github.com/amplication/plugins/blob/e8b38999d71c29303e856a269acf77a6522e3957/plugins/formatter-prettier/src/index.ts#L63

2024-01-12 11:38 UTC, Shurtu-gal requested changes
@pyxelpioneer Can you update the README to provide some more context as well as steps on how to startup the dev container after app is generated.

2024-01-12 11:38 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/src/static/admin.docker-compose.yml
> +      context: ../admin-ui
```suggestion
      context: .
```

2024-01-12 11:38 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/src/tests/.keep
@pyxelpioneer Tests can be added for various cases of settings.

2024-01-12 11:38 UTC, Shurtu-gal commented on plugins/devcontainer-github-codespaces/README.md
> +Generates the configuration that you require to setup devcontainer for your Amplication App
Duplicate of the earlier statement.

2024-01-18 05:27 UTC, Shurtu-gal commented
> @pyxelpioneer Can you update the README to provide some more context as well as steps on how to startup the dev container after app is generated.

@pyxelpioneer What I meant was adding steps on how to run the dev container after the service is made.

2024-01-20 12:47 UTC, Shurtu-gal requested changes

2024-01-20 12:48 UTC, Shurtu-gal commented
@overbit rest everything is fine by me. Could you have a look once too?

2024-01-23 18:47 UTC, mulygottlieb commented on plugins/devcontainer-github-codespaces/src/tests/.keep
Why do we need this?

2024-01-23 18:58 UTC, mulygottlieb reviewed
Nice work @pyxelpioneer !
I added one comment about an empty file in the tests directory, but other than that it LGTM.

2024-01-30 09:26 UTC, overbit approved these changes

2024-01-30 09:32 UTC, levivannoort commented
frok to branch

2024-01-30 10:49 UTC, levivannoort commented
Hey @pyxelpioneer I just checkout the plugin, built it locally and generated the application + plugin code. 

I decided to try both without and with the admin and a remark there is that if I run without it the plugin will still generate a pointer to the compose file (for a non generated part of the application): 

with:
```
"dockerComposeFile": [
  "../app/server/docker-compose.yml",
  "../app/admin/docker-compose.yml"
],
```
without:
```
"dockerComposeFile": [
  "../app/server/docker-compose.yml",
  "../app/admin/docker-compose.yml"
],
```

I'd also suggest to change the name of the directory created within the `.devcontainer` to use snake-case so that there are no spacers in the name generated by the plugin.

I'll also try to run the generated code via the dev container ang get back to you on that.

2024-01-30 11:35 UTC, overbit requested changes
@pyxelpioneer can you check @levivannoort comments as we identified a bug with the adminui.

In addition, to simplify the approval and release process, would you mind adding a short video here showing the GitHub Codespaces in action with a simple amplication generated app?

2024-03-17 18:12 UTC, Shurtu-gal commented
@pyxelpioneer any updates on this ?

2024-04-07 18:03 UTC, pyxelpioneer commented
Hey @overbit @Shurtu-gal, sorry for the extreme delay due to shifting, my codespace limit gettting full etc. Thanks for not closing this PR!

Here is the video showing the output based on the rework of the plugin.


https://github.com/amplication/plugins/assets/151645921/1259d3cf-f0b1-4d10-9a6b-aee0f37a5417

2024-04-14 13:45 UTC, pyxelpioneer commented
> Hey @overbit @Shurtu-gal @levivannoort , sorry for the extreme delay due to shifting, my codespace limit gettting full etc. Thanks for not closing this PR!
> 
> Here is the video showing the output based on the rework of the plugin.
> dance-2024-04-07_22.online-video-cutter.com.mp4

Hey @overbit ?

2024-04-15 08:58 UTC, overbit commented
Well done @pyxelpioneer! We are reviewing it.

2024-04-15 09:34 UTC, overbit approved these changes

2024-04-15 12:32 UTC, pyxelpioneer commented
> Well done @pyxelpioneer! We are reviewing it.

Thanks :heart_eyes:

2024-04-15 12:45 UTC, Shurtu-gal approved these changes

2024-04-15 12:46 UTC, Shurtu-gal commented
Great Work @pyxelpioneer!!!

2024-04-15 13:33 UTC, merged