Feat: plugin auth core
amplication/plugins pull request #41
Opened 2023-01-16 00:20 UTC by morhag90

2023-01-18 14:37 UTC, abrl91 commented on plugins/auth-api/src/index.ts
>    async afterCreateServerAuth(context: DsgContext) {
I suggest moving the functions to another file, so in the index.ts file, you will have only the imports that you need and the register() events

2023-01-22 10:31 UTC, tupe12334 commented on plugins/auth-api/src/util/nestjs-code-generation.ts
> +            builders.identifier("errors.ForbiddenException")
Why don't we use a calle AST object here instead of a string identifier

2023-01-22 10:33 UTC, tupe12334 commented on plugins/auth-api/src/util/nestjs-code-generation.ts
> +      accessibility: accessibility,
```suggestion
      accessibility,
```

2023-01-22 10:33 UTC, tupe12334 commented on plugins/auth-api/src/util/nestjs-code-generation.ts
> +        name: name,
```suggestion
        name,
```

2023-01-22 10:34 UTC, tupe12334 commented on plugins/auth-api/src/util/nestjs-code-generation.ts
> +export function addInjectableDependency(
Great work, I'm really impressed ;)

2023-01-25 09:07 UTC, overbit requested changes

2023-01-25 09:07 UTC, overbit commented on plugins/auth-api/package.json
>      "@nestjs/jwt": "^9.0.0",
Please use the version that is not affected by `jsonwebtoken` vulnerability
```suggestion
    "@nestjs/jwt": "^10.0.1",
```

2023-01-25 09:07 UTC, overbit commented on plugins/auth-api/package.json
> +    "passport-jwt": "4.0.0",
Please use the version that is not affected by `jsonwebtoken` vulnerability
```suggestion
    "passport-jwt": "^4.0.1",
```

2023-02-08 14:21 UTC, overbit submitted a review, later dismissed

2023-02-08 14:46 UTC, overbit approved these changes

2023-02-08 14:47 UTC, merged