fix(mongo): add default values
amplication/plugins pull request #85
Opened 2023-03-22 19:31 UTC by tupe12334

2023-03-22 19:33 UTC, yuval-hazaz approved these changes

2023-03-22 19:36 UTC, yuval-hazaz requested changes
please add description of the fix and a link to the issue

2023-03-22 21:07 UTC, overbit commented
Do we need a fix for mysql plugin too?

2023-03-23 08:26 UTC, tupe12334 commented
@overbit I tested it on the prod and its work, but anyhow, I think we want to use the same strategy for all of them

2023-03-24 08:41 UTC, overbit approved these changes

2023-03-24 08:42 UTC, merged